// File generated by FlutterFire CLI.
// ignore_for_file:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRh0VTmfAvrnv3vbdnzlSkj8-O-tg_Nw',
    appId: '1:266741697209:web:b822237b4b7b86140ee968',
    messagingSenderId: '266741697209',
    projectId: 'smart-water-bottle-iot',
    authDomain: 'smart-water-bottle-iot.firebaseapp.com',
    storageBucket: 'smart-water-bottle-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Km-RfwiBimztKLbT6Z_cGiyrIYWibpE',
    appId: '1:266741697209:android:5bc50efff7f11b740ee968',
    messagingSenderId: '266741697209',
    projectId: 'smart-water-bottle-iot',
    storageBucket: 'smart-water-bottle-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FaYhgFteXMSEOLkX_jERUqkOoU_R6-Q',
    appId: '1:266741697209:ios:b2c5c6df61a543820ee968',
    messagingSenderId: '266741697209',
    projectId: 'smart-water-bottle-iot',
    storageBucket: 'smart-water-bottle-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterBottleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FaYhgFteXMSEOLkX_jERUqkOoU_R6-Q',
    appId: '1:266741697209:ios:b2c5c6df61a543820ee968',
    messagingSenderId: '266741697209',
    projectId: 'smart-water-bottle-iot',
    storageBucket: 'smart-water-bottle-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterBottleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiRh0VTmfAvrnv3vbdnzlSkj8-O-tg_Nw',
    appId: '1:266741697209:web:f8e3ac5325aa863e0ee968',
    messagingSenderId: '266741697209',
    projectId: 'smart-water-bottle-iot',
    authDomain: 'smart-water-bottle-iot.firebaseapp.com',
    storageBucket: 'smart-water-bottle-iot.firebasestorage.app',
  );
}
